### PR TITLE
Version 1.0.2 - Update NAN version for 0.12/io compatibility.

### PR DESCRIPTION
**Pull request by voodootikigod**
Works!

### CODE REVIEW

**Comment by olizilla** [comment]
@voodootikigod <3
Are you benevolently fixing up modules for 0.12, or are you using it for a thing? I don't have my device handy so it might be a day or 2 before I can publish. I also accept video evidence / bribes to get it released sooner.

**Comment by voodootikigod** [comment]
using it in node-rolling-spider. Will send video proof!!!

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod | GitHub
http://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
RobotsConf http://robotsconf.com/ | RobotsWeekly
http://robotsweekly.com/

Help me end the negativity on the internet, share this
http://jsconf.eu/2011/an_end_to_negativity.html.

**Comment by voodootikigod** [comment]
In node-rolling-spider: https://youtu.be/D0etJSrqF4Q
Own tests: http://youtu.be/jZK356pgzqU

**Comment by olizilla** [comment]
RAD! THIS PR IS SPACECAT APPROVED.
space-cat

**Comment by olizilla** [comment]
@voodootikigod looks like we jumped from `1.0.0` to `1.0.2` is that for reasons? or just excite?

**Comment by olizilla** [comment]
huh, would you look at that. npm say I published 1.0.1 but no github records exist. I guess I must have been drunk or trying to update the readme or i have no idea what. 

Apologies for the delay, I shall publish forthwith.

**Pull request merged**
